# Content-related messages

content.content_missing=Noden sis\u00E4lt\u00F6 puuttuu: \n   node: {0} \n   lukija: {1}  \n   Ota yhteytt\u00E4 yll\u00E4pitoon.
content.runtime_exec.property_moved=Ominaisuus ''errorCodes'' on siirretty RuntimeExec -luokkaan

index.recovery.out_of_date=Indeksit eiv\u00E4t ole synkassa tietokannan kanssa.
index.tracking.starting=Indeksien palautus aloitettu.
index.tracking.complete=Indeksien palautus valmis.
index.tracking.progress=\tK\u00E4sitell\u00E4\u00E4n siirtymi\u00E4 {0}.
index.recovery.starting=Indeksien palautus aloitettu: {0} siirtym\u00E4\u00E4.
index.recovery.complete=Indeksien palautus valmis.
index.recovery.progress=\t{0} % valmis.
index.recovery.terminated=Indeksien palautus keskeytetty.

node.archive.msg.busy=Palautusoperaatio on k\u00E4ynniss\u00E4

content.http_reader.err.no_connection=Alfresco-palvelimeen ei saada yhteytt\u00E4 HTTP:n kautta: {0}
content.http_reader.err.no_authentication=HTTP-lukija ei pystynyt autentikoitumaan palvelimella: {0}  \n
content.http_reader.err.check_cluster=Varmista ett\u00E4 'replicateUpdates' ja 'replicateUpdatesViaCopy' ovat enabloitu cachelle 'org.alfresco.cache.ticketsCache'.  Tarkista ett\u00E4 klusterikonfiguraatio on oikeanlainen ja toimii.
content.http_reader.err.unrecognized=Tunnistamaton virhe tapahtui ladattaessa sis\u00E4lt\u00F6\u00E4 palvelimelta:\n   Server: {0} \n   Content: {1} \n   HTTP-response: {2}

metadata.extraction.err.type_conversion=Metadatan ker\u00E4\u00E4minen ep\u00E4onnistui koska arvo ei ollut vaadittua tyyppi\u00E4: \n   Extractor: {0} \n   Target Property QName: {1} \n   Required Type: {2} \n   Extracted Value: {3}

transform.err.format_or_password=Sis\u00E4ll\u00F6n konvertoiminen ep\u00E4onnistui mahdollisesti v\u00E4\u00E4rin formatoidun tai salasanasuojatun tiedoston takia.

content.routing.err.invalid_default_store=''defaultStoreName'', ''{0}'' ei viittaa t\u00E4m\u00E4n sis\u00E4lt\u00F6\u00F6n: ''storesByName'' ({1}).